name: ${project.name}
description: ${project.description}
version: ${project.version}
api-version: 1.13

main: com.songoda.epicenchants.EpicEnchants
softdepend:
  - PlaceholderAPI
  - PlayerPoints
  - UltimateBottles
  - Vault

author: Craftaro
website: ${project.url}

# TODO: Fix the stuff below (ussage?, why ee and not epicenchants?, etc.)
commands:
  ee:
    aliases:
      - epicenchants
    ussage: reload
