name: ${project.name}
description: ${project.description}
version: ${project.version}
api-version: 1.13

main: com.songoda.epicenchants.EpicEnchants
softdepend:
  - PlaceholderAPI
  - PlayerPoints
  - UltimateBottles
  - Vault

author: Songoda
website: ${project.url}

commands:
  ee:
    aliases:
      - epicenchants
    ussage: reload
