name: EpicEnchants
version: maven-version-number
main: com.songoda.epicenchants.EpicEnchants
authors: [Songoda]
website: https://songoda.com/
softdepend: [Vault, PlayerPoints, UltimateBottles, PlaceholderAPI]
api-version: 1.13
commands:
  epicenchants:
    aliases: [ee]
    ussage: /ee reload